# This file is included in the http context by Elastic Beanstalk
# It cannot define server blocks (EB handles that)
# Instead, we use map to set variables that can be used in EB's server blocks

# Map for redirect logic
map $http_x_forwarded_proto $redirect_to_https {
    default 0;
    'http' 1;
}
